CREATE TABLE MULTINACIONAL (
      CODMULTINACIONAL NUMBER(3) PRIMARY KEY,
      NOMBREEMPRESA VARCHAR2(20),
      NOMBREJEFE VARCHAR2(20),
      NOMBREEMPLEADO VARCHAR2(20),
      SUELDONETO NUMBER(5),
      EDAD NUMBER(2),
      FECHA DATE,
      CATEGORIA VARCHAR2(15)
);
CREATE TABLE CICLOS (
      CODCICLO NUMBER(3) PRIMARY KEY,
      NOMCICLO VARCHAR2(20),
      NUMALUMNO NUMBER(2),
      NUMAPROBT1 NUMBER(2),
      NUMAPROBT2 NUMBER(2),
      NUMAPROBT3 NUMBER(2)
);
INSERT INTO CICLOS VALUES(001,'DAM1',10,5,6,10);
INSERT INTO CICLOS VALUES(002,'DAM2',5,4,3,10);
INSERT INTO CICLOS VALUES(003,'DAW1',15,5,6,1);
INSERT INTO CICLOS VALUES(004,'DAW2',10,3,2,1);
INSERT INTO CICLOS VALUES(005,'FINANZAS',12,1,2,3);
INSERT INTO CICLOS VALUES(006,'MARKETING',13,5,5,4);
SELECT CODCICLO, NOMCICLO FROM CICLOS WHERE NOMCICLO LIKE'DAM%';
SELECT COUNT(NUMAPROBT1) FROM CICLOS WHERE NUMAPROBT1>=5;
SELECT NUMAPROBT1 FROM CICLOS WHERE NUMAPROBT1>=5;
SELECT SUM(NUMALUMNO), AVG(NUMALUMNO) FROM CICLOS;
ALTER TABLE CICLOS (NUMAPROBFINAL NUMBER(2));
UPDATE CICLOS SET NUMAPROBFINAL=8 WHERE CODCICLO=001;
UPDATE CICLOS SET NUMAPROBFINAL=8 WHERE CODCICLO=002;
UPDATE CICLOS SET NUMAPROBFINAL=8 WHERE CODCICLO=003;
UPDATE CICLOS SET NUMAPROBFINAL=9 WHERE CODCICLO=004;
UPDATE CICLOS SET NUMAPROBFINAL=9 WHERE CODCICLO=005;
UPDATE CICLOS SET NUMAPROBFINAL=9 WHERE CODCICLO=006;
UPDATE CICLOS SET NUMALUMNO=15 WHERE NOMCICLO LIKE'DAM%';

INSERT INTO MULTINACIONAL VALUES (001,'GETRONICS','LUIS PERES','ANTONIO',1500,25,TO_DATE('2000-10-06', 'YYYY-MM-DD'),'TECNICO');
INSERT INTO MULTINACIONAL VALUES (002,'GETRONICS','JULIAN MARTIN','LUIS',2100,27,TO_DATE('2001-11-07', 'YYYY-MM-DD'),'ANALISTA');
INSERT INTO MULTINACIONAL VALUES (003,'ATOS','ANTONIO FERNANDEZ','JAVIER',2100,28,TO_DATE('2005-12-08', 'YYYY-MM-DD'),'ANALISTA');
INSERT INTO MULTINACIONAL VALUES (004,'ALBA','JOSE RODRIGEZ','MARTA',1000,29,TO_DATE('2003-11-08', 'YYYY-MM-DD'),'OPERADOR');
INSERT INTO MULTINACIONAL VALUES (005,'ALBA','JOSE RODRIGEZ','JULIAN',1500,27,TO_DATE('2003-10-08', 'YYYY-MM-DD'),'TECNICO');
INSERT INTO MULTINACIONAL VALUES (006,'ALBA','JOSE RODRIGEZ','CARLOS',1500,25,TO_DATE('2004-11-28', 'YYYY-MM-DD'),'TECNICO');
INSERT INTO MULTINACIONAL VALUES (007,'ALBA','LUIS RODRIGEZ','MARIA',1500,29,TO_DATE('2004-11-18', 'YYYY-MM-DD'),'TECNICO');
INSERT INTO MULTINACIONAL VALUES (008,'ALBA','LUIS RODRIGEZ','PEPE',1000,29,TO_DATE('2005-11-08', 'YYYY-MM-DD'),'OPERADOR');
INSERT INTO MULTINACIONAL VALUES (009,'ALBA','LUIS RODRIGEZ','MARCOS',2100,25,TO_DATE('2003-11-08', 'YYYY-MM-DD'),'ANALISTA');
INSERT INTO MULTINACIONAL VALUES (010,'ALBA','LUIS RODRIGEZ','PEDRO',2100,29,TO_DATE('2005-11-08', 'YYYY-MM-DD'),'ANALISTA');
SELECT NOMBREEMPRESA, NOMBREJEFE FROM MULTINACIONAL;
SELECT * FROM MULTINACIONAL WHERE CATEGORIA='ANALISTA';
SELECT NOMBREJEFE, NOMBREEMPLEADO FROM MULTINACIONAL WHERE NOMBREEMPRESA='GETRONICS';
SELECT NOMBREJEFE, NOMBREEMPLEADO FROM MULTINACIONAL WHERE CATEGORIA='ANALISTA' ORDER BY NOMBREEMPRESA;
SELECT NOMBREJEFE, NOMBREEMPLEADO FROM MULTINACIONAL WHERE CATEGORIA='ANALISTA' ORDER BY NOMBREJEFE;
SELECT NOMBREJEFE, NOMBREEMPLEADO FROM MULTINACIONAL WHERE SUELDONETO<=1800;
SELECT NOMBREJEFE, NOMBREEMPLEADO FROM MULTINACIONAL WHERE FECHA>='2002-01-01' AND FECHA<'2020-01-01';
SELECT COUNT(CATEGORIA) FROM MULTINACIONAL WHERE CATEGORIA='TECNICO';