CREATE TABLE ALUMNOSNUEVO
( CODALUMNO NUMBER(3) NOT NULL,
 NOMALUMNO VARCHAR(30) NOT NULL,
 NOTAT1 NUMBER (2),
 NOTAT2 NUMBER (2),
 NOTAT3 NUMBER (2),
 EDAD NUMBER (2),
 CONSTRAINT pk_alumnos PRIMARY KEY (CODALUMNO),
 CONSTRAINT ck1_alumnos CHECK ( NOTAT1 between 1 and 10),
 CONSTRAINT ck2_alumnos CHECK ( NOTAT2 between 1 and 10),
 CONSTRAINT ck3_alumnos CHECK ( NOTAT3 between 1 and 10),
 CONSTRAINT ck4_alumnos CHECK ( EDAD between 1 and 99)
);
INSERT INTO ALUMNOSNUEVO VALUES (001,'LUIS',10,5,6,22);
INSERT INTO ALUMNOSNUEVO VALUES (002,'ANTONIO',5,4,3,23);
INSERT INTO ALUMNOSNUEVO VALUES (003,'PEPE',10,5,6,12);
INSERT INTO ALUMNOSNUEVO VALUES (004,'MARIA',10,3,2,34);
INSERT INTO ALUMNOSNUEVO VALUES (005,'JOSE',10,3,2,34);
INSERT INTO ALUMNOSNUEVO VALUES (006,'SOFIA',10,5,5,44);
DESCRIBE ALUMNOSNUEVO;
INSERT INTO ALUMNOSNUEVO VALUES (007,'FEDE',13,5,5,44);

INSERT INTO ALUMNOSNUEVO VALUES (008,'ANOTNIO',10,10,10,10);
DELETE FROM ALUMNOSNUEVO WHERE CODALUMNO=008;

DROP TABLE ALUMNOSNUEVO;
CREATE TABLE ALUMNOSNUEVO
( CODALUMNO NUMBER(3) NOT NULL,
NOMALUMNO VARCHAR(30) NOT NULL,
NOTAT1 NUMBER (2),
NOTAT2 NUMBER (2),
NOTAT3 NUMBER (2),
EDAD NUMBER (2),
SEXO VARCHAR(2),
CONSTRAINT pk_alumnos PRIMARY KEY (CODALUMNO),
CONSTRAINT ck1_alumnos CHECK ( NOTAT1 between 1 and 10),
CONSTRAINT ck2_alumnos CHECK ( NOTAT2 between 1 and 10),
CONSTRAINT ck3_alumnos CHECK ( NOTAT3 between 1 and 10),
CONSTRAINT ck4_alumnos CHECK ( EDAD between 1 and 99),
CONSTRAINT ck5_alumnos CHECK (SEXO='H' OR SEXO='M')
);
INSERT INTO ALUMNOSNUEVO VALUES (001,'LUIS',10,5,6,22,'H');
INSERT INTO ALUMNOSNUEVO VALUES (002,'ANTONIO',5,4,3,23,'H');
INSERT INTO ALUMNOSNUEVO VALUES (003,'PEPE',10,5,6,12,'H');
INSERT INTO ALUMNOSNUEVO VALUES (004,'MARIAJ',10,3,2,34,'M');
INSERT INTO ALUMNOSNUEVO VALUES (005,'JOSEJ',10,3,2,34,'H');
INSERT INTO ALUMNOSNUEVO VALUES (0006,'SOFIA',10,5,5,44,'M');

ALTER TABLE ALUMNOSNUEVO ADD CONSTRAINT ck6_alumnosnuevo CHECK (LENGTH(NOMALUMNO)<=10);

