CREATE TABLESPACE "EXAMEN" LOGGING
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\EXAMEN.dbf' SIZE 24M 
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


DROP USER espgonda CASCADE;

CREATE USER espgonda IDENTIFIED BY alumno
       DEFAULT TABLESPACE EXAMEN
       TEMPORARY TABLESPACE temp
       ACCOUNT UNLOCK;

GRANT "CONNECT" TO espgonda;
GRANT "RESOURCE" TO espgonda;

GRANT ALTER ANY INDEX TO espgonda;
GRANT ALTER ANY SEQUENCE TO espgonda;
GRANT ALTER ANY TABLE TO espgonda;
GRANT ALTER ANY TRIGGER TO espgonda;
GRANT CREATE ANY INDEX TO espgonda;
GRANT CREATE ANY SEQUENCE TO espgonda;
GRANT CREATE ANY SYNONYM TO espgonda;
GRANT CREATE ANY TABLE TO espgonda;
GRANT CREATE ANY TRIGGER TO espgonda;
GRANT CREATE ANY VIEW TO espgonda;
GRANT CREATE PROCEDURE TO espgonda;
GRANT CREATE PUBLIC SYNONYM TO espgonda;
GRANT CREATE TRIGGER TO espgonda;
GRANT CREATE VIEW TO espgonda;
GRANT DELETE ANY TABLE TO espgonda;
GRANT DROP ANY INDEX TO espgonda;
GRANT DROP ANY SEQUENCE TO espgonda;
GRANT DROP ANY TABLE TO espgonda;

