SET SERVEROUTPUT ON;
BEGIN
      DBMS_OUTPUT.PUT_LINE('HOLA HOLA HOLITA. ESTOY EMPEZANDO CON PLSQL');
END;

DECLARE
    A NUMBER;
    B NUMBER;
    C NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMANDO NUMERICOS');
    A:=&IntroduceNumero1;
    B:=&IntroduceNumero2;
    C:=A+B;
    DBMS_OUTPUT.PUT_LINE('LA SUMA ES '|| C);
END;

DECLARE
  A NUMBER;
  B NUMBER;
  MAYOR NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('SUMANDO NUMERICOS VERSION 2.0');
  A:=&INTRODUCENUMERO1;
  B:=&INTRODUCENUMERO2;
  IF A>B THEN
    MAYOR:=A;
  ELSE
    MAYOR:=B;
  END IF;
  DBMS_OUTPUT.PUT_LINE('EL MAYOR ES '||MAYOR);
END;

CREATE OR REPLACE PROCEDURE ImprimirMensaje
IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('hola hola holita, creando procedimientos en plsql');
END;

EXECUTE ImprimirMensaje;

CREATE OR REPLACE PROCEDURE Sumando2Numeros (A NUMBER, B NUMBER)
IS C NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('HOLA HOLITA, VAMOS A SUMAR DOS NUMERITOS');
  C:=A+B;
  DBMS_OUTPUT.PUT_LINE('LA SUMA DE LOS NUMERITOS ES '||C);
END;

EXECUTE SUMANDO2NUMEROS (5, 2);

CREATE OR REPLACE PROCEDURE mayoromenor (A NUMBER, B NUMBER)
IS MAYOR NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('VAMOS A VER QUE NUMERICO ES MAYOR');
  IF A>B THEN
    MAYOR:=A;
  ELSE IF
    MAYOR:=B;
  END IF;
  DBMS_OUTPUT.PUT_LINE('EL MAYOR ES '||MAYOR);
END;

EXECUTE MAYOROMENOR (10,5);

CREATE OR REPLACE PROCEDURE holacaracola 
IS A NUMBER:=0
BEGIN
  FOR A IN 0..3 LOOP
    DBMS_OUTPUT.PUT_LINE('HOLA HOLA CARA DE COLA');
  END LOOP;
END;

EXECUTE HOLACARACOLA;


CREATE OR REPLACE PROCEDURE HOLOCARACOLO (A NUMBER:=0)
IS
BEGIN
  WHILE (A<=3) LOOP
    DBMS_OUTPUT.PUT_LINE('HOLO HOLO CARA DE COLO');
    A:=A+1;
  END LOOP;
END;

EXECUTE HOLOCARACOLO;

CREATE OR REPLACE PROCEDURE HOLACARACOLA2
IS A NUMBER:=0; B NUMBER:=0;
BEGIN
  WHILE (A<=3) LOOP
    DBMS_OUTPUT.PUT_LINE('FEDE NO TIENES RAZON');
    A:=A+1;
  END LOOP;
END;
EXECUTE HOLACARACOLA2;

DECLARE
  A NUMBER;
BEGIN
  FOR A IN 0..10 LOOP
    HOLACARACOLA;
  END LOOP;
END;


CREATE OR REPLACE PROCEDURE ImprimirMensaje2 (texto VARCHAR2)
IS
BEGIN
  DBMS_OUTPUT.PUT_LINE(texto);
END;
EXECUTE ImprimirMensaje2 ('base de datos');
EXECUTE ImprimirMensaje2 ('plsql');

CREATE OR REPLACE PROCEDURE ImprimirMensajeCualquiera (n NUMBER, texto VARCHAR2)
IS A NUMBER;
BEGIN
  FOR A IN 1..n LOOP
    DBMS_OUTPUT.PUT_LINE(texto);
  END LOOP;
END;
EXECUTE ImprimirMensajeCualquiera (5, 'base de datos');

CREATE OR REPLACE PROCEDURE SucesionDeNumeros
IS A NUMBER;
BEGIN
  FOR A IN 1..5 LOOP
    DBMS_OUTPUT.PUT_LINE(A);
  END LOOP;
END;
EXECUTE SucesionDeNumeros;

CREATE OR REPLACE PROCEDURE SucesionDeNumerosHasta (B NUMBER)
IS A NUMBER;
BEGIN
  FOR A IN 1..B LOOP
    DBMS_OUTPUT.PUT_LINE(A);
  END LOOP;
END;
EXECUTE SucesionDeNumerosHasta (&Introducedatos);

create or replace 
PROCEDURE SucesionDeNumerosPares (B NUMBER)
IS A NUMBER:=0;
BEGIN
  WHILE A<=B LOOP
    A:=A+1;
    IF MOD(A,2)!=0 THEN
      DBMS_OUTPUT.PUT_LINE('NUMERO '||A);
    END IF;
  END LOOP;
END;
EXECUTE SucesionDeNumerosImpares (&Introducedatos);

create or replace 
PROCEDURE SucesionDeNumerosPares (B NUMBER)
IS A NUMBER:=0;
BEGIN
  WHILE A<=B LOOP
    A:=A+1;
    IF MOD(A,2)=0 THEN
      DBMS_OUTPUT.PUT_LINE('NUMERO '||A);
    END IF;
  END LOOP;
END;
EXECUTE SucesionDeNumerosPares (&Introducedatos);

CREATE OR REPLACE PROCEDURE Multiplos (B NUMBER)
IS A NUMBER:=0;
BEGIN
  DBMS_OUTPUT.PUT_LINE('LOS MULTIPLOS DE '||B||' son:');
  WHILE A<B LOOP
    A:=A+1;
    IF MOD(B,A)=0 THEN
      DBMS_OUTPUT.PUT_LINE(A);
    END IF;
  END LOOP;
END;
EXECUTE Multiplos(10);
EXECUTE Multiplos(20);

create or replace 
PROCEDURE NumMayor (A NUMBER, B NUMBER, C NUMBER)
IS MAYOR NUMBER;
BEGIN
  IF A>B THEN
    IF A>C THEN
      MAYOR:=A;
    ELSE
      MAYOR:=C;
    END IF;
  ELSE IF B>C THEN
    MAYOR:=B;
   END IF;
  END IF;
  DBMS_OUTPUT.PUT_LINE('El mayor es '||MAYOR);
END;
EXECUTE NumMayor(&IntroduceA, &IntroduceB, &IntroduceC);
EXECUTE NumMayor(5,7,6);

create or replace 
PROCEDURE NumerosMayorMenor (A NUMBER, B NUMBER, C NUMBER)
IS MAYOR NUMBER; MEDIANO NUMBER; MENOR NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('A CONTINUACION SE ORDENARAN LOS NUMEROS DE MAYOR A MENOR');
  IF A>B AND B>C THEN
    MAYOR:=A;
    MEDIANO:=B;
    MENOR:=C;
  END IF;
  IF A>B AND C>B THEN
    MAYOR:=A;
    MEDIANO:=C;
    MENOR:=B;
  END IF;
  IF A>B AND A<C THEN
    MAYOR:=C;
    MEDIANO:=A;
    MENOR:=B;
  END IF;
  IF C>A AND B>C THEN
    MAYOR:=C;
    MEDIANO:=B;
    MENOR:=A;
  END IF;
  IF B>C AND C>A THEN
    MAYOR:=B;
    MEDIANO:=C;
    MENOR:=A;
  END IF;
  IF B>C AND A>C THEN
    MAYOR:=B;
    MEDIANO:=A;
    MENOR:=C;
  END IF;
    DBMS_OUTPUT.PUT_LINE('LOS NUMEROS ORDENADOS SON: '||MAYOR||'-'||MEDIANO||'-'||MENOR);
END;
EXECUTE NumerosMayorMenor (10,8,12);
EXECUTE NumerosMayorMenor (&IntroduceNum1, &IntroduceNum2, &IntroduceNum3);

CREATE OR REPLACE PROCEDURE SumaMediaParImpar (A NUMBER)
IS RESULTADO NUMBER:=0; I NUMBER:=0;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Suma, media, pares, impares');
  FOR I IN 0..A LOOP
    RESULTADO:=RESULTADO+I;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('Suma: '||RESULTADO);
  DBMS_OUTPUT.PUT_LINE('Media: '||RESULTADO/A);
  RESULTADO:=0;
  FOR I IN 0..A LOOP
    IF MOD(I,2)=0 THEN
      RESULTADO:=RESULTADO+I;
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('La suma de los pares es: '||RESULTADO);
  RESULTADO:=0;
  FOR I IN 0..A LOOP
    IF MOD(I,2)!=0 THEN
      RESULTADO:=RESULTADO+I;
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('La suma de los impares es: '||RESULTADO);
END;
EXECUTE SumaMediaParImpar(&IntroduceNumero);

CREATE OR REPLACE PROCEDURE Potencia (A NUMBER, B NUMBER)
IS RESULTADO NUMBER:=1; I NUMBER;
BEGIN
  FOR I IN 0..B-1 LOOP
    RESULTADO:=RESULTADO*A;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(A||' elevado a '||B||' es '||RESULTADO);
END;
EXECUTE Potencia (&IntroduceBase, &IntroduceExponente);

DECLARE
BEGIN
  NumerosMayorMenor (&IntroduceNum1, &IntroduceNum2, &IntroduceNum3);
  SumaMediaParImpar (&IntroduceNumero);
  Potencia (&IntroduceBase, &IntroduceExponente);
END;

CREATE OR REPLACE PROCEDURE Factorial(A NUMBER)
IS FACTORIAL NUMBER:=1; I NUMBER:=A;
BEGIN
  DBMS_OUTPUT.PUT('A continuacion se calculara el factorial de '||A||' -> ');
  WHILE I>0 LOOP
    FACTORIAL:=FACTORIAL*I;
    I:=I-1;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(FACTORIAL);
END;
EXECUTE Factorial(&IntroduceNumero);

CREATE OR REPLACE PROCEDURE TablasMultiplicar
IS A NUMBER:=1; B NUMBER:=1; RESULTADO NUMBER;
BEGIN
  FOR A IN 1..9 LOOP
    B:=1;
    DBMS_OUTPUT.PUT_LINE('-------');
    DBMS_OUTPUT.PUT_LINE('TABLA DEL '||A);
    DBMS_OUTPUT.PUT_LINE('-------');
    FOR B IN 1..10 LOOP
      RESULTADO:=A*B;
      DBMS_OUTPUT.PUT_LINE(A||'x'||B||'='||RESULTADO);
    END LOOP;
  END LOOP;
END;
EXECUTE TablasMultiplicar;
    
CREATE OR REPLACE PROCEDURE VisualizarLetras (PALABRA VARCHAR2)
IS RESULTADO VARCHAR2(1); I NUMBER;
BEGIN
  FOR I IN 0..LENGTH(PALABRA) LOOP
    RESULTADO:=SUBSTR(PALABRA,I,I+1);
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
  END LOOP;
END;

DECLARE
  PALABRA VARCHAR2(25);
BEGIN
 VisualizarLetras (&Introducepalabra);
END;